import TranscoderZenRTCManager, {
  EVT_DESTROYED,
  EVT_PEER_CONNECTED,
  EVT_PEER_DISCONNECTED,
  EVT_PEER_DESTROYED,
  EVT_PEER_UPDATED,
} from "./TranscoderZenRTCManager";

export default TranscoderZenRTCManager;
export {
  EVT_DESTROYED,
  EVT_PEER_CONNECTED,
  EVT_PEER_DISCONNECTED,
  EVT_PEER_DESTROYED,
  EVT_PEER_UPDATED,
};
