import ChromeZenRTCPeer, {
  EVT_CONNECTING,
  EVT_CONNECTED,
  EVT_DISCONNECTED,
  EVT_DESTROYED,
  EVT_DATA_RECEIVED,
  EVT_OUTGOING_MEDIA_STREAM_TRACK_ADDED,
  EVT_OUTGOING_MEDIA_STREAM_TRACK_REMOVED,
  EVT_INCOMING_MEDIA_STREAM_TRACK_ADDED,
  EVT_INCOMING_MEDIA_STREAM_TRACK_REMOVED,
  EVT_SYNC_EVT_RECEIVED,
} from "./ChromeZenRTCPeer";

export default ChromeZenRTCPeer;
export {
  EVT_CONNECTING,
  EVT_CONNECTED,
  EVT_DISCONNECTED,
  EVT_DESTROYED,
  EVT_DATA_RECEIVED,
  EVT_OUTGOING_MEDIA_STREAM_TRACK_ADDED,
  EVT_OUTGOING_MEDIA_STREAM_TRACK_REMOVED,
  EVT_INCOMING_MEDIA_STREAM_TRACK_ADDED,
  EVT_INCOMING_MEDIA_STREAM_TRACK_REMOVED,
  EVT_SYNC_EVT_RECEIVED,
};

/*
import ChromeZenRTCPeerMonitor, {
  EVT_PEER_CONNECTED,
  EVT_PEER_DISCONNECTED,
  EVT_PEER_DATA_RECEIVED,
  EVT_PEER_MONITOR_INCOMING_MEDIA_STREAM_TRACK_ADDED,
  EVT_PEER_MONITOR_INCOMING_MEDIA_STREAM_TRACK_REMOVED,
  EVT_PEER_MONITOR_OUTGOING_MEDIA_STREAM_TRACK_ADDED,
  EVT_PEER_MONITOR_OUTGOING_MEDIA_STREAM_TRACK_REMOVED,
  EVT_PEER_MONITOR_SYNC_EVT_RECEIVED,
} from "./ChromeZenRTCPeerMonitor";

export default ChromeZenRTCPeer;

export {
  ChromeZenRTCPeerMonitor,
  EVT_DATA_RECEIVED,
  EVT_PEER_CONNECTED,
  EVT_PEER_DISCONNECTED,
  EVT_PEER_DATA_RECEIVED,
  EVT_PEER_MONITOR_INCOMING_MEDIA_STREAM_TRACK_ADDED,
  EVT_PEER_MONITOR_INCOMING_MEDIA_STREAM_TRACK_REMOVED,
  EVT_PEER_MONITOR_OUTGOING_MEDIA_STREAM_TRACK_ADDED,
  EVT_PEER_MONITOR_OUTGOING_MEDIA_STREAM_TRACK_REMOVED,
  EVT_PEER_MONITOR_SYNC_EVT_RECEIVED,
};
*/
