export default [
  "Screaming Frog SEO Spider/2.22",
  "Fever/1.38 (Feed Parser; http://feedafever.com; Allow like Gecko)",
  "Mozilla/5.0 (compatible; archive.org_bot/3.3.0 +http://pandora.nla.gov.au/crawl.html)",
  "Mozilla/5.0 (compatible; NetcraftSurveyAgent/1.0; +info@netcraft.com)",
  "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0); 360Spider",
  "Tiny Tiny RSS/1.10 (http://tt-rss.org/)",
  "SAMSUNG-SGH-E250/1.0 Profile/MIDP-2.0 Configuratio…ebot-Mobile/2.1; +http://www.google.com/bot.html)",
  "RamblerMail/6.0 (incompatible; ImageProxy/6.0)",
  "larbin_2.6.3 larbin2.6.3@unspecified.mail",
  "Mozilla/5.0 (compatible; FlipboardProxy/1.2; +http://flipboard.com/browserproxy)",
  "Mozilla/5.0 (compatible; AhrefsBot/5.0; +http://ah…de.google.com/appengine; appid: s~proxyfile1-hrd)",
  "rogerbot/1.0 (http://www.moz.com/dp/rogerbot, rogerbot-crawler@moz.com)",
  "Mozilla/5.0 (compatible; special_archiver/3.1.1 +http://www.archive.org/details/archive.org_bot)",
  "ApacheBench/2.3",
  "Mozilla/5.0 (Windows; U; Windows NT 5.1;fr;rv:1.8.…oilaBotCollector BETA 0.1 (http://www.voila.com/)",
  "sentry/8.6.0 (https://getsentry.com)",
  "OpenWebSpider v0.1.4 (http://www.openwebspider.org/)",
  "Baiduspider+(+http://www.baidu.com/search/spider.htm)",
  "bitlybot/3.0",
  "HTTPMon/1.0b (http://www.httpmon.com)",
  "MSNBot/Nutch-1.5.1",
  "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/535.1 (KH…ogle_partner_monitoring FWSzVTDDBz14547302713138T",
  "Mozilla/5.0 (compatible; Exabot/3.0 (BiggerBetter); +http://www.exabot.com/go/robot)",
  "facebookplatform/1.0 (+http://developers.facebook.com)",
  "Sogou web spider/4.0(+http://www.sogou.com/docs/help/webmasters.htm",
  "Mozilla/5.0 (compatible; BountiiBot/1.1; +http://bountii.com/contact.php)",
  "Mozilla/5.0 (compatible; YandexVerticals/1.0; http://yandex.com/bots)",
  "Mozilla/5.0 (compatible; coccoc/1.0; +http://help.coccoc.com/)",
  "Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS…ebot-Mobile/2.1; +http://www.google.com/bot.html)",
  "Spider/Nutch-2.3-SNAPSHOT (Webcrawler)",
  "Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://yandex.com/bots)",
  "Mozilla/5.0 (compatible; Genieo/1.0 http://www.genieo.com/webfilter.html)",
  "Mozilla/5.0 (compatible; OrangeBot-Collector/2.0; support.orangebot@orange.com)",
  "Tarmot Gezgin/1.0 (compatible; TarmotGezgin/1.1; +http://www.tarmot.com/gezgin)",
  "Mozilla/5.0 (compatible; URLAppendBot/1.0; +http://www.profound.net/urlappendbot.html)",
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) Ap…ecko) Version/8.0.2 Safari/600.2.5 (Applebot/0.1)",
  "Mozilla/5.0 (compatible; BazQux/2.4; +https://bazqux.com/fetcher; 2 subscribers)",
  "Mozilla/5.0 (compatible; Gluten Free Crawler/1.0; +http://glutenfreepleasure.com/)",
  "nlcrawler/1.0 (+http://northernlight.com/)",
  "mozilla/5.0 (compatible; heritrix/1.3.0 http://archive.crawler.org)",
  "Mozilla/5.0 (compatible; heritrix/1.14.4 +http://www.dla-marbach.de)",
  "FeedBurner/1.0 (http://www.FeedBurner.com)",
  "SimplePie/1.2.1-dev (Feed Parser; http://simplepie.org; Allow like Gecko) Build/20130514092120",
  "yacybot (freeworld/global; x86 Windows XP 5.1; java 1.7.0_21; GMT+04:00/ru) http://yacy.net/bot.html",
  "GoogleProducer; (+http://goo.gl/7y4SX)",
  "msnbot-media/1.1 (+http://search.msn.com/msnbot.htm)",
  "W3C_Validator/1.767",
  "Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-CN; rv:1.9.2.8) Firefox/3.6.8/Nutch-1.7",
  "Mozilla/5.0 (compatible; YandexBlogs/0.99; robot; B; +http://yandex.com/bots)",
  "Mozilla/5.0 (Java) outbrain",
  "WebbCrawler 1.0 ( http://badcheese.com/crawler.html )",
  "Mozilla/5.0 (compatible; Wappalyzer; +https://github.com/AliasIO/Wappalyzer)",
  "AppEngine-Google; (+http://code.google.com/appengine; appid: s~snapchat-proxy)",
  "Mozilla/5.0 (compatible; YandexImageResizer/2.0; +http://yandex.com/bots)",
  "IP-Guide.com Crawler/1.0 (https://ip-guide.com)",
  "Mozilla/5.0 (compatible; CareerBot/1.1; +http://www.career-x.de/bot.html)",
  "Zookabot/2.5;++http://zookabot.com",
  "SSL Labs (https://www.ssllabs.com/about/assessment.html)",
  "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)",
  "MetaInspector/5.4.0 (+https://github.com/jaimeiniesta/metainspector)",
  "Mozilla/5.0 (compatible; archive.org_bot; Wayback …ord; +http://archive.org/details/archive.org_bot)",
  "Mozilla/4.0 (compatible; Netcraft Web Server Survey)",
  "PHPCrawl",
  "testnutch/Nutch-1.8",
  "Mozilla/5.0 (compatible; worio bot heritrix/1.10.0 +http://worio.com)",
  "NewsBlur Page Fetcher - 7 subscribers - http://www… (KHTML, like Gecko) Version/5.1 Safari/534.48.3)",
  "Googlebot-News (2.3.3, ruby 1.9.3 (2013-11-22))",
  "5acd734a-1ed3-4a17-ad9d-0b09ae7bc2d2/Nutch-1.7",
  "kouio.com RSS reader",
  "Google-Structured-Data-Testing-Tool +https://search.google.com/structured-data/testing-tool)",
  "MySpider/Nutch-2.2",
  "AhrefsBot.Feeds v0.1; http://ahrefs.com/",
  "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; baidu Transcoder;)",
  "Mozilla/5.0 (compatible; BLEXBot/1.0; +http://webmeup-crawler.com/)",
  "Mozilla/5.0 (compatible; spbot/4.0.9; +http://OpenLinkProfiler.org/bot )",
  "Mozilla/5.0 (compatible; Qwantify/2.2w; +https://www.qwant.com/)/*",
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36…oogle Web Preview) Chrome/27.0.1453 Safari/537.36",
  "W3C-checklink/4.0 [4.4] libwww-perl/5.803",
  "SensikaBot/x.33 (+http://sensika.com)",
  "Bloglovin/1.0 (http://www.bloglovin.com; 1 subscribers)",
  "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)",
  "Mozilla/5.0 (compatible; MJ12bot/v1.4.4; http://www.majestic12.co.uk/bot.php?+)",
  "flieder - neofonie heritrix/1.14.3 (+http://spider.neofonie.de)",
  "Mozilla/5.0 (compatible; Dataprovider/6.92; +https://www.dataprovider.com/)",
  "Mozilla/5.0 (compatible; rogerBot/1.0; UrlCrawler; http://www.seomoz.org/dp/rogerbot)",
  "TweetedTimes Bot/1.0 (Mozilla/5.0 Compatible, +http://tweetedtimes.com)",
  "W3C-mobileOK/DDC-1.0 (see http://www.w3.org/2006/07/mobileok-ddc)",
  "Mozilla/5.0 (Windows NT 6.1; rv:6.0) Gecko/2011081…e (+https://developers.google.com/+/web/snippet/)",
  "WordPress/4.7.2; https://example.com",
];
