import WebIPCMessageBroker, {
  EVT_READY_STATE_CHANGED,
  EVT_MESSAGE_RECEIVED,
  EVT_DESTROYED,
  TYPE_WEB_IPC_MESSAGE,
} from "./WebIPCMessageBroker";

export default WebIPCMessageBroker;
export {
  EVT_READY_STATE_CHANGED,
  EVT_MESSAGE_RECEIVED,
  EVT_DESTROYED,
  TYPE_WEB_IPC_MESSAGE,
};
