name: ci
"on":
  - push
  - pull_request
jobs:
  test:
    name: Node ${{ matrix.node }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment: ci
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }} # Source branch of the pull request if the event that triggers the run is a pull_request
      - run: bash ./test.sh
      - run: cp .env.sample .env
      - run: bash ./build.prod.sh
