name: ci
"on":
  - push
  - pull_request
jobs:
  test:
    name: Node ${{ matrix.node }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment: ci
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "main" # @see https://github.com/peter-evans/create-pull-request/issues/122#issuecomment-601337482
      - run: NODE_ENV=development bash ./test.sh
      - run: bash ./build.prod.sh
