name: ci
"on":
  - push
  - pull_request
jobs:
  test:
    name: Node ${{ matrix.node }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment: ci
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git checkout HEAD^ # Fix: fatal: ref HEAD is not a symbolic ref (likely caused by forced commits)
      - run: bash ./test.sh
      - run: bash ./build.prod.sh
